CXX=g++
CXXFLAGS=-g -Wall -std=c++17
LINKER_FLAGS =
OBJS = main.cpp DirectoryManager.cpp FileManager.cpp FolderMGMT.cpp
OBJ_NAME = Console_Folder_Mgmt

all : $(OBJS)
	$(CXX) $(OBJS) $(CXXFLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
